### ISSUE TITLE
Id Markers

### ISSUE THREAD

**Issue by tonsig** [jcmellado/js-aruco#10]
Hello Juan, I am studying the JS-Aruco library and saw how to generate the fiducial marks; however, I am unable to get the ID of the markers as captured in the image. Do you have any link with the example? (Found in the generation of markers, a reference to markers [0] .id, however, it seems that this attribute is not instantiated by default in AR.detector).

**Comment by jcmellado** [comment]
The main page of the project (https://github.com/jcmellado/js-aruco) has some links with examples. It includes some references about the usage of the library too.

Basic demo: http://inmensia.com/files/aruco/getusermedia/getusermedia.html Full source code: https://github.com/jcmellado/js-aruco/tree/master/samples/getusermedia
