### ISSUE TITLE
How to generate other markers?

### ISSUE THREAD

**Issue by jabrena** [jcmellado/js-aruco#14]
Hi,

I am testing the project and I would like to generate other markers.
Does exist some tool to generate a marker?

Currently in the output, the visualizaiton show a value, using this marker:
https://camo.githubusercontent.com/f55430b914e27388021304f4741f39285158b4bb/687474703a2f2f7777772e696e6d656e7369612e636f6d2f66696c65732f70696374757265732f65787465726e616c2f313030312e706e67

How to store another value?

Many thanks in advance

Juan Antonio

**Comment by Suriv** [comment]
+1

**Comment by jabrena** [comment]
Hi, 

surfing on internet, I found the solution:
http://diogok.net/js-aruco-markers/index.html

This library is great!

Merry Christmas.

Juan Antonio
