### ISSUE TITLE
sorting the contours

### ISSUE THREAD

**Issue by prakash047** [jcmellado/js-aruco#16]
Hi,

Thumbs Up..!! for the amazing scripts.

I would like know if there is a method to get the number of pixels in a contour.

Thanks in advance.

**Comment by jcmellado** [comment]
Not sure what are you looking for.

Maybe the cv.perimeter function.

**Comment by prakash047** [comment]
sorry for not being clear, Actually I was looking to sort the contours based on 

1.  left to right. (x co-ordinate)  (or)
2. based on number of pixels in that contour.

**Comment by jcmellado** [comment]
1. The contour object has a list of pixel coordinates, iterate over it and find the minimum x
2. Pixels on the perimeter of the contour? Then maybe the cv.perimeter function could do the trick.
Pixels on the area delimited by the contour? Then maybe you should use some sort of [flood filling algorithm](https://en.wikipedia.org/wiki/Flood_fill)
