### ISSUE TITLE
equivalent of boudingRect for width and height of the contouore

### ISSUE THREAD

**Issue by prakash047** [jcmellado/js-aruco#17]
HI,

is there an equivalent function in js for boundingRect?

is there a way to get the width and height of the contour?

**Comment by jcmellado** [comment]
OpenCV has [maskBoundingRect](
https://github.com/opencv/opencv/blob/master/modules/imgproc/src/shapedescr.cpp#L582). It would be easy to port it to JavaScript.

But now I not sure if you are talking about the "raw contours" (i.e. free hand) of the "processed contours" (i.e. detected marker)

Some years ago I wrote some short "Spanish" articles about it:
http://inmensia.com/blog/20110527/realidad_aumentada_douglas_peucker.html

Automatic English translation:
https://translate.google.es/translate?sl=es&tl=en&js=y&prev=_t&hl=es&ie=UTF-8&u=http%3A%2F%2Finmensia.com%2Fblog%2F20110527%2Frealidad_aumentada_douglas_peucker.html&edit-text=
