### ISSUE TITLE
Difference between posit1.js and posit2.js

### ISSUE THREAD

**Issue by jeromeetienne** [jcmellado/js-aruco#20]
Hey,

i love the simplicity of aruco! im considering adding it as backend for [AR.js](https://github.com/jeromeetienne/ar.js). So i may have some questions :)

the first one is: what is the difference between posit1 and 2 ? You seems to use [posit1 in your code](https://github.com/jcmellado/js-aruco/blob/master/samples/debug-posit/debug-posit.html#L9)

Thanks

**Comment by jcmellado** [comment]
The first one (posit1) is explained here:
http://www.cfar.umd.edu/~daniel/daniel_papersfordownload/CoplanarPts.pdf

And the second one (posit2) here:
http://www.aforgenet.com/articles/posit/

Credits and links are in posit1.js and posit2.js.

Both are really very similar, there are some differences about error calculations, but I don't remember now the details.

**Comment by jeromeetienne** [comment]
Thanks for your prompt answer!

**Comment by jeromeetienne** [comment]
btw an update - im working on js-aruco and more especially on the thresholding side.

This is 75% of the whole time on a 640x480 images according to my measurement.

But this is running on a single thread of cpu. and in javascript.

Im trying to see how WebAssembly and webworker could help, more on that later :)

stuff are happening here. https://github.com/jeromeetienne/AR.js/blob/master/three.js/examples/imageProcessing.wasm/TODO.md

**Comment by jcmellado** [comment]
Great
