### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by Fuzzyma** [jcmellado/js-aruco#21]
There wasnt a contribution in teh last two years. I would be really happy to have aruco available in javascript. @jcmellado What are the chances this lib get updated?

**Comment by jcmellado** [comment]
Well, the library is working.

No issues, and only one recent pull request to add a package,json.

So... ?

**Comment by Fuzzyma** [comment]
You have a point there :). My question aimed to new possible versions of aruco (I think they are at 2.0.17 now?). And yes - a package.json would be awesome :)

**Comment by jcmellado** [comment]
Latest Aruco 2.x version changelog:

> - Added the Dictionary concept which  allows to use the most famous fiducial marker approaches : ARUCO,APRILTAGS,ARTAG and ARTOOLKIT+. These are hardcoded so you only have to select the one you need.
> - Parallelization improved and some other optimizations added
> - Boards are now replaced by the concept of MarkerMap which is a more general concept.
> Not relevant for the JavaScript version
> - Added classes for tracking the camera pose. 
> - Chessboard patterns are now allowed
> - Calibration tool included

Not really excited about that, maybe the optimizations.

But the C++ code have changed a lot of from the original one I ported **six** years ago.

**Comment by jorgerobles** [comment]
Love it. I'm wondering about using to fine place a work on a DIY laser cutter using an endoscope camera. Hope can get to work the estimation to get precision placement.
