### ISSUE TITLE
Perspective transformation based on markers position

### ISSUE THREAD

**Issue by davoscript** [jcmellado/js-aruco#22]
Hi, @jcmellado and thanks for this amazing library.

I wonder if it's possible to apply a perspective transformation using the CV.js methods, I tried using `CV.warp` (and converting the returned array into a **Uint8ClampedArray**), but I'm having trouble with the `warpSize` parameter.

My goal is to remove the perspective distortion of the image (I have aruco codes in each corner), any help would be much appreciated.

Thanks!

**Comment by jcmellado** [comment]
Could you show us your (relevant) code?

**Comment by jcmellado** [comment]
Hmmm... looking at the Aruco code, I see that it is using a fixed value for `warpSize` (49)

**Comment by yvesbuschor** [comment]
I'm trying to achieve the exact same thing. @davoscript did you get the transformation to work already? Or do you maybe have a code snippet of how you're using CV.wrap?

Any help to get me started in the right direction is much appreciated!
