### ISSUE TITLE
Scanning 3x3 marker

### ISSUE THREAD

**Issue by jaykumarthaker** [jcmellado/js-aruco#23]
Awesome work, loved it man!

Had tried with 7X7 marker and works like a charm.

Just one question, I have gone through your documentation and you have stated clearly that it will work on 7X7 marker, whereas here I am in the need of scanning 3X3 marker, so how would I achieve that?

Frankly speaking I am novice, so please try to be nice with me on this. Any help would be appreciated. 👍 :)

Thank you so much in advance.

**Comment by jcmellado** [comment]
Hmmm, 3x3 is just black or white, that's a lot of false positives.

Anyway, you should modify some functions in the aruco.js file.
- `getMarker`: Converts a detected square into a 7x7 array of 1s and 0s 
- `hammingDistance`: Checks if an array contains a valid combination (see [Hamming distance](https://en.wikipedia.org/wiki/Hamming_distance))
- `mat2id`: Converts the sequence of detected 1s and 0s into an id
