### ISSUE TITLE
Suggestion on better pose estimation ?

### ISSUE THREAD

**Issue by jeromeetienne** [jcmellado/js-aruco#24]
js-aruco is great at detecting the markers. It is fast and simple, i love it :)

It is a little less cool about the pose estimation, using posit1 or posit2 seems to produce significant inaccuracies unfortunatly. So it makes it unsuitable to add some 3d on top of the marker without having significant issues. 

Is it me using it poorly ? (i experience it even on the examples of this repository too)

I would love to help or to implement other alternative for pose estimation... but im a bit lost on which algo to implement. Can you suggest which one i could use ?

Any suggestion would be great :)

**Comment by jcmellado** [comment]
You could start reading the "Tracking the position of a marker" and "Benefits of using Marker Maps" sections from here: https://www.uco.es/investiga/grupos/ava/node/26

**Comment by jcmellado** [comment]
See #25
