### ISSUE TITLE
Marker id more than 1023

### ISSUE THREAD

**Issue by livindead** [jcmellado/js-aruco#27]
Hello)
Please help, i am develop ar kids book and me need more than 1024 marker. How can i increase the count of the marker id?

**Comment by jcmellado** [comment]
Sadly, you can't. At least you can't do it in an easy way. It would be necessary to modify the library.

**Comment by livindead** [comment]
So sad ...
Tell me please in which direction to work?

**Comment by jcmellado** [comment]
Not sure what you are asking for, but I would look for another library.
