### ISSUE TITLE
Obtaining Camera Pos from Aruco Marker?

### ISSUE THREAD

**Issue by frastlin** [jcmellado/js-aruco#29]
Hello,
How can I obtain the camera pos and orientation based off the marker? I am trying to move from OpenCV, and there the [SolvePnP function](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#bool%20solvePnP(InputArray%20objectPoints,%20InputArray%20imagePoints,%20InputArray%20cameraMatrix,%20InputArray%20distCoeffs,%20OutputArray%20rvec,%20OutputArray%20tvec,%20bool%20useExtrinsicGuess,%20int%20flags)) returns the camera pos based off the marker.

**Comment by jcmellado** [comment]
Take a look to the "3D Pose Estimation" section:
https://github.com/jcmellado/js-aruco#3d-pose-estimation

There is a demo too:
https://jcmellado.github.io/js-aruco/debug-posit/debug-posit.html

**Comment by frastlin** [comment]
Thank you, this works great for detecting a single 5X5 marker.

1. How can we change the marker type to a 4X4 or other sized marker?
2. How can we add more detailed information about the camera, such as the X and Y focal length calibration or camera distortion coefficients?
3. coplanar means that all the points in the model need to be in a single plane. I'm putting multiple Aruco markers on objects and they are not all on the same plane. How can I perform pose estimation with markers that are not all on the same plane? This is what the SolvePnP function does from OpenCv.

**Comment by jcmellado** [comment]
1. The library only works with 5x5 markers.

2. There are no such option to do it.

3. The pose estimator can be called for each marker.
