### ISSUE TITLE
Aruco & Aruco2 freeze on 1st frame on Safari-iOS

### ISSUE THREAD

**Issue by VinceThom** [jcmellado/js-aruco#31]
Hello!

The demos of Aruco and Aruco2 both freeze on the first frame on Safari / iOS. I tried on two iPhones.  

https://jcmellado.github.io/js-aruco/getusermedia/getusermedia.html
and 
https://damianofalcioni.github.io/js-aruco2/samples/getusermedia/getusermedia_ARUCO.html

Thanks for the great work!
See the section _Safari freezing_: https://stackoverflow.com/questions/63084076/ios13-getusermedia-not-working-on-chrome-and-edge

**Comment by jcmellado** [comment]
Sorry, I don't have any iOS device for testing.

Note: I have tested the demo on an Android device with Chrome and it worked (after allowing camera access to Chrome).

**Comment by Utopiah** [comment]
Hi there, any help I could provide to try to get it working on iOS?
