### ISSUE TITLE
What marker to use

### ISSUE THREAD

**Issue by alduxvm** [jcmellado/js-aruco#8]
Hi!

What marker to use in order to work? I the one in the readme file and did not work (https://camo.githubusercontent.com/f55430b914e27388021304f4741f39285158b4bb/687474703a2f2f7777772e696e6d656e7369612e636f6d2f66696c65732f70696374757265732f65787465726e616c2f313030312e706e67) 3D Pose Estimation...

thanks a lot!

**Comment by jcmellado** [comment]
I pointed my webcam to your marker and it worked fine:

![image](https://cloud.githubusercontent.com/assets/6494060/8164937/bb152740-138c-11e5-8397-82e3968270c3.png)
