### ISSUE TITLE
How to create custom AR codes?

### ISSUE THREAD

**Issue by antonioaguilar** [jcmellado/js-aruco#9]
Hi Juan,
Just wanted to say that JS-Aruco is a great library - I have been experimenting with it for the last few days. I have a question, how do you create the AR codes with custom IDs? Do you have or use some software the you can recommend? thanks, 
Antonio.

**Comment by jcmellado** [comment]
I don't use any software, I just draw them with a making pen.

Anyway, there are some tools out there, but I haven't tested any of them:
https://github.com/diogok/js-aruco-markers
https://github.com/bhollis/aruco-marker
